### ISSUE TITLE
"Find Use" doesn't working for me.

### ISSUE THREAD

**Issue by damonto** [erichard/SublimePHPCompanion#116]
I got an error when `allow_use_from_global_namespace` is True.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "php_companion.commands.find_use_command in /Users/DamonTo/Library/Application Support/Sublime Text 3/Installed Packages/PHP Companion.sublime-package", line 17, in run
  File "php_companion.utils in /Users/DamonTo/Library/Application Support/Sublime Text 3/Installed Packages/PHP Companion.sublime-package", line 40, in find_symbol
  File "php_companion.utils in /Users/DamonTo/Library/Application Support/Sublime Text 3/Installed Packages/PHP Companion.sublime-package", line 49, in find_in_global_namespace
AttributeError: 'module' object has no attribute 'STARTUPINFO'

```

If `allow_use_from_global_namespace` is False. There is no problem.

**Comment by erichard** [comment]
Hi @damonto 

The latest release should fix this problem.

**Comment by damonto** [comment]
I tried upgrade PHP Companion to latest release. but this problem still so.

**Comment by jpmurray** [comment]
Hello,

I'm setuping a new workstation (as of tonight), pulled my usual packages (of which PHP Companion is on of!) and placed my keybindings and stumbled across this too. Tried other commands and it's like they won't fire up. I'm not sure if I was on the latest version before on my last setup, but now it's just not working.

Using the console I can attest that the correct keybinding is sent, and that the command is fired (`key evt: super+e` and `command: find_use` appears in console with proper setting enabled`), but that it, nothing happens in my file.

Is there any log I can pull somewhere to try and help solving this?

**Comment by ethanclevenger91** [comment]
Same issue here. Also of note, on Windows, a CMD window opens for a split second, and it seems to be running a PHP script (title bar ends in php.exe). Immediately closes, nothing happens. Also verified command is firing via the console.

**Comment by ethanclevenger91** [comment]
Well this is now working. Entirely unsure what I changed, if anything...
